Implement methods of `RequestHandler` for `App`
restless-rs/restless pull request #17
Opened 2023-06-20 05:35 UTC by gr3yknigh1

* Implement `RequestHandler` methods for `App`
* Change signature of HTTP method function in order to be compatible with types in `Route` struct (leaved this for later)

Close #15

2023-06-20 06:35 UTC, gregor-tokarev requested changes
Wait until this pr https://github.com/restless-rs/restless/pull/16 will be merged, then pass into function

2023-06-20 06:35 UTC, gregor-tokarev commented on restless/src/route_handler.rs
> +    fn get(&mut self, path: &'static str, handler: fn()) -> &mut Self;
Wait until this pr https://github.com/restless-rs/restless/pull/16 will be merged, then pass into this `fn()` functions type declarations request and response structs

2023-06-20 10:28 UTC, alytidae approved these changes

2023-06-28 01:44 UTC, gregor-tokarev approved these changes

2023-06-28 01:50 UTC, merged