added build_request_path method in App struct and changed privacy of …
restless-rs/restless pull request #7
Opened 2023-05-18 00:03 UTC by igor2323

…fields in many structs in file route.rs

2023-05-18 05:48 UTC, gregor-tokarev requested changes
Add test, that fails, but shouldn't

2023-05-18 05:48 UTC, gregor-tokarev commented on restless/src/app.rs
> +            for i in 0..route.paths.len(){
Why iterating by index, you can just `for route in route.paths` and access route directly instead of route.paths[i]

2023-05-18 05:48 UTC, gregor-tokarev commented on restless/src/app.rs
> +        let req_paths: Vec<&str> = req.path.split_terminator("/").collect();
Would be better if you change it with:
`let req_paths = req.path.split_terminator("/").collect::<Vec<_>>();`

2023-05-18 18:01 UTC, igor2323 commented on restless/src/app.rs
> +            for i in 0..route.paths.len(){
You're right, will change

2023-05-18 18:06 UTC, igor2323 commented on restless/src/app.rs
> +        let req_paths: Vec<&str> = req.path.split_terminator("/").collect();
Ok, np

2023-05-18 18:13 UTC, gr3yknigh1 approved these changes
Seems good to me. Approve

2023-05-18 18:19 UTC, gr3yknigh1 approved these changes

2023-05-18 18:26 UTC, gr3yknigh1 approved these changes

2023-05-22 02:37 UTC, gregor-tokarev approved these changes
done

2023-05-22 09:04 UTC, merged